### PR TITLE
Fix incorrect dips check in `slope_estimation

### LINKED ISSUE #572: incorrect check on dips argument in in `slope_estimation
The documentation states the following: 

image

However, the logic flow in the code is the opposite:

https://github.com/PyLops/pylops/blob/0d19f5689978cb71e743bf673d4ce775e22817c6/pylops/utils/signalprocessing.py#L249-L253

I double checked with the original implementation of `dips_estimate` 

https://github.com/PyLops/pylops/blob/c5844c4a4b25cdb74a5cef12b926d6d91da20095/pylops/utils/signalprocessing.py#L79-L182

And it is inline with the current documentation. It appears that the bug was introduced when `dips_estimate` and slope_estimate` merged.  

I have a PR ready for this.

### PR DESCRIPTION
**Pull request by Beramos**
closes #572. 

Quick fix but I have also added a unit test to see if the regularisation is applied when NOT using dips as a way to check which algorithm is used.

### CODE REVIEW

**Comment by mrava87** [comment]
Adding @cako here

**Comment by mrava87** [comment]
Alright, great! Then we can merge this :)

**Comment by mrava87** [comment]
Thanks @Beramos, I can merge this now :)

**Comment by Beramos** [comment]
@mrava87, awesome!

**Pull request merged**
