### PR TITLE
Added Abstraction to `_matvec` and `_rmatvec`

### PR DESCRIPTION
**Pull request by rohanbabbar04**
PR for issue #369 
- Created a New abstract Class `BaseLinearOperator` which extends the LinearOperator with abstract methods `_matvec` and `_rmatvec`. 
- Made all the classes extend the new `BaseLinearOperator`
-  In `docs/source/conf.py` changes were made because of flake8

### CODE REVIEW

**Comment by dikwickley** [comment]
@rohanbabbar04 i don't think you should be changing the `makefile`. Also, a lot of your updates are just indentations. maybe try turning off your formatter?

**Comment by rohanbabbar04** [comment]
> @rohanbabbar04 i don't think you should be changing the `makefile`. Also, a lot of your updates are just indentations. maybe try turning off your formatter?

I have reverted the MakeFile, I changed it before but its the same

**Comment by rohanbabbar04** [comment]
@mrava87 do take a look..

**Comment by mrava87** [comment]
thanks a lot for the PR!

In general I think you changed a lot of files, some do not have anything to do with the goal of the PR (eg `conf.py` file for the documentation), so we may ask you to do a clean PR or we can work on this and squash things at the end :)

@cako and I will make a review and get back to you.

**Comment by rohanbabbar04** [comment]
> thanks a lot for the PR!
> 
> In general I think you changed a lot of files, some do not have anything to do with the goal of the PR (eg `conf.py` file for the documentation), so we may ask you to do a clean PR or we can work on this and squash things at the end :)
> 
> @cako and I will make a review and get back to you.

I have removed the `conf.py` formatting changes, maybe it was because of my formatter. Rest all files are related to the PR

**Comment by cako** [comment]
Hi! Awesome that this is looked into, hopefully we can get somewhere we are all comfortable with. With that said, I think users having to derive from a new class is not great. It would require releasing a new version for example. One possibility is to have LinearOperator be a metaclass, or at least set _rmatvec and _matvec as abstract methods in it? I'm not sure that's feasible and would like to hear your opinions on it.

**Comment by mrava87** [comment]
This is what I hoped/tried before but I gave the error in the GitHub issue mentioned above - see for error message.

My understanding at that time was that since LinearOperator has direct dependency on the scipy LinearOperator that

**Comment by cako** [comment]
One suggestion might be to explore a [mixin structure](https://www.pythontutorial.net/python-oop/python-mixin/) where BaseLinearOperator only provides some methods.

**Comment by mrava87** [comment]
Does this still use the ABCMeta concept? In other words, can you have methods that are mandatory and will raise error at class instantiation like for the ABC approach?

**Comment by rohanbabbar04** [comment]
> One suggestion might be to explore a [mixin structure](https://www.pythontutorial.net/python-oop/python-mixin/) where BaseLinearOperator only provides some methods.

I think this will do away with the `ABCMeta` approach and like @mrava87 mentioned some classes have a direct dependency on LinearOperator for functions like `_adjoint`.

**Comment by mrava87** [comment]
Perhaps we should explore what would it take to reach this goal https://github.com/PyLops/pylops/issues/328 first. It will ideally allow us to make LinearOperator the meta class directly instead of relying on 3 base classes :)

**Comment by marcusvaltonen** [comment]
> 

I haven't had so much time to look at this, but considering the current approach with the usage of `aslinearoperator()`, I do think the cleanest approach is to get rid of the dependency on `spLinearOperator`. I would have to dig deeper to see if you could do something about it without sacrificing this.

**Comment by mrava87** [comment]
@rohanbabbar04 probably it is a good time now to go back to this given our new definition of LinearOperator.. it should be much easier now to accomplish this task.

Peraphs make a brand new PR as most of this code is now obsolete :)

**Comment by rohanbabbar04** [comment]
Ok @mrava87 I'll make a new PR

**Pull request closed without merging**
