### PR TITLE
Fix bug in dottest for imag

### PR DESCRIPTION
**Pull request by mrava87**
Resolve https://github.com/PyLops/pylops/issues/229.

### CODE REVIEW

**Comment by ar4** [comment]
Looks good.

Is there a reason to use `dot` instead of `vdot`, and to have a separate closeness check, when the values are real? Would the code written for the complex cases work as well (since the imaginary parts will just be zero)?

**Comment by mrava87** [comment]
Great :) No, I suspect this should be the same, probably `dot ` is a bit faster as it doesn't do checks but I guess the overhead is tiny. For the closeness check it is more to have a print statement that doesn't have the images where there is no imag - so it is a bit cleaner. Of course, we could do the check at print stage but I think there is no way out having a check somewhere unless we always want to print real and imag even when we know the latter is 0.

Tests pass with `vdot`, I can make a PR taking that `if... else` away.

**Comment by ar4** [comment]
Does it not print the real and imaginary parts the way that you want if you just print the value (without the `.real` and `.imag`)? If it did, then the same print statement might work for both the real and complex cases.

**Comment by mrava87** [comment]
Yes :)

What I meant was that so far we have this for real numbers:
```
print('Dot test failed, v^T(Opu)=%f - u^T(Op^Tv)=%f' % (yy, xx))
```
and this for complex:
```
print('Dot test passed, v^T(Opu)=%f%+fi - u^T(Op^Tv)=%f%+fi' % (yy.real, yy.imag, xx.real, xx.imag))
```

if we have only one print statement we will always get something like ``v^T(Opu)=3+0j - u^T(Op^Tv)=2+0j`` instead of ``v^T(Opu)=3 - u^T(Op^Tv)=2``. I am not sure if this is worth of extra checks or if we should just let it print always with the imag part even if it is zero. What do you think?

**Comment by ar4** [comment]
Ah, do you wish to keep using that style of Python print statement for backwards compatibility? With the newer ones the print statement will automatically print without the imaginary part if the value is real:
```
a = 1 + 2j
b = 3
print('a={}, b={}'.format(a, b)) # a=(1+2j), b=3
print(f'a={a}, b={b}') # a=(1+2j), b=3
```

**Comment by mrava87** [comment]
Oh right, good point.

It is more an historical reason, I think we should switch to f-strings but since we have quite some prints it is a matter of time and priority. In that case, you are right the all real/complex story will become much easier to handle.

Let's reopen https://github.com/PyLops/pylops/issues/229 as a reminder of this discussion and hopefully we can go for a switch in print statements in coming months :)

**Comment by mrava87** [comment]
Created a new dedicated issue https://github.com/PyLops/pylops/issues/283

**Pull request merged**
