### PR TITLE
ci: full restyling of CI pipelines

### PR DESCRIPTION
**Pull request by mrava87**
This PR introduces a full restyling to our CI pipeline:

- [x] removed `.travis.yml` since our Travis-CI always runs out of free token (and I always need to ask to get more... too tedious process). Also have 2 CIs (Github Action and Azure Pipelines air) should be good enough, no need for 3.
- [x] added `macos-latest` to our Github Action `build` and 4 python versions (from 3.7 to 3.10)
- [x] created a new Github Action `codacy-coverage-reporter` to upload coverage to Codacy. This runs tests only for one python version on ubuntu

### CODE REVIEW

**Comment by cako** [comment]
I will let you merge this one when you're done!

**Comment by mrava87** [comment]
Sure, no worries. So far it doesn’t work, I just opened an issue: https://github.com/codacy/codacy-coverage-reporter-action/issues/69

**Comment by mrava87** [comment]
@cako I am running out of ideas what I am doing wrong with `codacy-coverage-reporter-action`. 

I use this as recommended on Codacy (I also looked at one project using it, I don't see any difference other than of course I dont know how they have setup their `CODACY_PROJECT_TOKEN`: https://raw.githubusercontent.com/haddocking/prodigy/main/.github/workflows/ci.yml

I tried locally following https://docs.codacy.com/coverage-reporter/ as I was afraid maybe I am using the wrong token but it works, so I wonder if I am doing something wrong when I set it in Github. Still no reply from my Github issue on the `codacy-coverage-reporter-action` GitHub project... so we are alone! Do you mind taking a look when you have time, you should be able to access everything in Github since you are also admin, not sure about Codacy.... if you also fail, I am tempted to remove the Codacy-coverage for the moment.

PS: I decided to change the scope of the PR and make it a bit broader.. we were in need of some restyling of our CI, have a look at the top, where I explain what I have added/changed

**Comment by mrava87** [comment]
Ok, I may have found out why!!

From the Action secrets page:

```
Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork.
```

Let me try accepting the pull request and see.

**Pull request merged**
