### PR TITLE
Documentation migration and New Theme 

### PR DESCRIPTION
**Pull request by dikwickley**
issue: #443 
@mrava87 I have updated the python version to `python 3.9` and also updated the theme to `pydata-sphix-theme`
I hosted it as well for testing: https://dikwickley-pylops.readthedocs.io/en/latest/
(I know there are a lot of commits if you want me to make a fresh PR let me know)
please review the PR

### CODE REVIEW

**Comment by dikwickley** [comment]
@mrava87 any idea why the codacy static code analysis failed?

**Comment by mrava87** [comment]
Nice work @dikwickley :) Give me a few days to look into it, at first I really like it and I agree with the choice of new template.

I think Codacy does not fails because of your changes, but it consistently fails as some of our code does not conform to their 'rules'. Compared to workflows testing the code, we use the Codacy workflow more as a tool to help us, so I wouldn't worry :)

**Comment by mrava87** [comment]
For the commits, let us review this PR and then once its ready you can either squash them into one or make a fresh PR

**Comment by mrava87** [comment]
@dikwickley I had a look at your changes and I have no comments. Also this PR triggered a build on rtd and everything seem to have run successfully :)

If you can squash all commits into one (as I suspect some change things back and forth) than I can approve it.

Btw, not sure why (maybe you have set git locally with another username/email) but if you look above in this page you will see ‘[aniketinfocusp](https://github.com/aniketinfocusp) added 11 commits’…

**Comment by dikwickley** [comment]
hey @mrava87 sure i'll make a fresh new PR. ah yes, i didn't realize, i made those changes using my work laptop at the office not realizing it was using my work git. I'll make the new PR using my local computer.

**Pull request closed without merging**
