### PR TITLE
#335 and #336; but backwards compatible

### PR DESCRIPTION
**Pull request by prisae**
#335 and #336; but backwards compatible - just as discussed in #336

### CODE REVIEW

**Comment by mrava87** [comment]
Mmh, I worry this isn't 100% backward compatible, or at least not for someone choosing to use positional arguments. Can we keep `tol` for `rtol` and just add `atol` as last input parameter :)

**Comment by prisae** [comment]
This is backwards compatible for both positional and keyword arguments @mrava87 - otherwise many tests would fail!

**Comment by mrava87** [comment]
Oh I see now, sorry my bad!

Can you please just change the versionadded thing I commented on and then it’s good to go :)

**Comment by prisae** [comment]
What do you mean with "the versionadded thing"?

I did add `versionadded` for `atol`, and `deprecated` for `tol`; I did not do anything for `rtol`, because I thought it is not a change in functionality (nor position), just the name changed. Do you want me to add a `versionadded` by `rtol`?
```
    atol : :obj:`float`, optional
        Absolute dottest tolerance
        .. versionadded:: 2.0.0
    tol : :obj:`float`, optional
        Dottest tolerance
        .. deprecated:: 2.0.0
            Use ``rtol`` instead.
```

**Comment by prisae** [comment]
Oh, I realize that I wrote `versionadded:: 2.0.0`, but it should be `1.18.????`?

**Comment by mrava87** [comment]
Yep, this is what I meant as this will go into a v1.8.1 :)

**Comment by mrava87** [comment]
Alright, I let the tests finish and merge.

Thanks a lot 🚀

**Pull request merged**
